CN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400,handler404,handler403,handler500
import debug_toolbar

handler400 = 'CN.views.bad_request'
handler403 = 'CN.views.permission_denied'
handler404 = 'CN.views.page_not_found'
handler500 = 'CN.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.master.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('empresas/', include('apps.empresas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('datos/', include('apps.datos.urls')),
    path('reportes/', include('apps.reportes.urls')),
    path('parametros/', include('apps.parametros.urls')),
    path('puntos_medicion/', include('apps.puntos_medicion.urls')),
    path('plantillas/', include('apps.plantillas.urls')),
    path('licencias/', include('apps.licencias.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index ,name='index'),
    path('menu', views.menu ,name='menu'),
    path('cpu', views.cpu,name='cpu'),
]

apps/reportes/urls.py
from django.urls import  path
from . import views

app_name = "reportes"

urlpatterns = [
    path('', views.index, name="index"),
    path('get_form/', views.get_form, name="get_form"),
    path('get_datos/', views.get_datos, name="get_datos"),
]

apps/reportes/models.py
from django.db import models

# Create your models here.

apps/reportes/views.py
from django.contrib import messages
from django.db.models.aggregates import Sum
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse
from apps.datos.models import Datos
from apps.plantillas.models import Plantilla
from apps.puntos_medicion.models import PuntoMedicion
from apps.parametros.models import Parametro
import datetime,json

# Create your views here.
@login_required(login_url='/')
def index(request):
    fecha_ini = request.GET.get('fecha_ini')
    fecha_fin = request.GET.get('fecha_fin')
    if not fecha_ini or not fecha_fin:
        date_ini = datetime.date.today()
        date_fin = datetime.date.today()
    else:
        date_ini = datetime.datetime.strptime(fecha_ini, '%Y-%m-%d').date()
        date_fin = datetime.datetime.strptime(fecha_fin, '%Y-%m-%d').date()
    if date_ini > date_fin:
        messages.error(request, 'La fecha inicial no puede ser mayor a la fecha final.')
        return redirect('datos:index')
    plantillas = Plantilla.objects.filter(empresa=request.user.empresa, activo=True)
    context = {
        'appname' : "reportes",
        'fecha_ini' : fecha_ini,
        'fecha_fin' : fecha_fin,
        'plantillas' : plantillas,
    }
    return render(request, "reportes/formulario_datos.html", context)

@login_required(login_url='/')
def get_form(request):
    if request.method == "GET":
        pk_plantilla = request.GET.get('plantilla')
        plantilla = Plantilla.objects.get(pk=pk_plantilla)
        puntos = PuntoMedicion.objects.filter(tipo=plantilla.tipo, empresa=request.user.empresa)
        parametros = Parametro.objects.filter(tipo=plantilla.tipo)
        fechas_existentes = Datos.objects.filter(plantilla=plantilla).values('fecha').distinct().order_by('fecha')
        datos_json = {}
        puntos_list = []
        parametros_list = []
        for punto in puntos:
            puntos_list.append({
                'nombre' : punto.nombre,
                'id' : punto.id,
            })
        for parametro in parametros:
            parametros_list.append({
                'nombre' : parametro.nombre,
                'id' : parametro.id,
            })
        datos_json['puntos'] = puntos_list
        datos_json['parametros'] = parametros_list
        #convert fechas_existentes to json
        fechas_existentes_json = []
        for fecha in fechas_existentes:
            fechas_existentes_json.append(fecha['fecha'])
        datos_json['fechas'] = fechas_existentes_json

        return JsonResponse(datos_json, safe=False)
    return JsonResponse({})

@login_required(login_url='/')
def get_datos(request):
    if request.method == "POST":
        datos_json = {}
        fecha_ini = request.POST.get('fecha_ini')
        fecha_fin = request.POST.get('fecha_fin')
        plantilla = request.POST.get('plantilla')
        puntos = request.POST.getlist('puntos')
        parametros = request.POST.getlist('parametros')
        plantilla = Plantilla.objects.get(pk=plantilla)
        parametros_list = []
        puntos_list = []
        for p in puntos:
            puntos_list.append(PuntoMedicion.objects.get(pk=p))
        for parametro in parametros:
            parametro = Parametro.objects.get(pk=parametro)
            parametros_list.append(parametro)
            datos_json[parametro.id] = []
            for punto in puntos:

                punto = PuntoMedicion.objects.get(pk=punto)
                datos = Datos.objects.filter(punto_medicion=punto, parametro=parametro, fecha__range=[fecha_ini, fecha_fin],plantilla=plantilla)
                #order by fecha asc
                datos = datos.order_by('fecha')
                datos_json[parametro.id].append({
                    'id' : punto.id,
                    'punto' : punto.nombre,
                    'data' : [],
                })
                #append to punto.nombre  dato.fecha and dato.valor to datos_json
                for dato in datos:
                    datos_json[parametro.id][-1]['data'].append({
                        'fecha' : dato.fecha.strftime('%Y-%m-%d'),
                        'valor' : dato.valor,
                    })
        datos_json = json.dumps(datos_json)
        context = {
            'appname' : "reportes",
            'datos_json' : datos_json,
            'puntos' : puntos_list,
            'parametros' : parametros_list,
        }
        return render(request, "reportes/grafico_datos.html", context)
    return redirect('datos:index')

templates/reportes/formulario_datos.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>

</div>
<div class="row">
    <div class="col-xl-12 col-md-12 mb-12">
        <button type="button" class="btn btn-primary mb-4" data-bs-toggle="modal" data-bs-target="#modal">
            Fechas Existentes
        </button>
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Seleccione Elementos</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div style="width: 100%;">
                    <form action="{% url 'reportes:get_datos' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group ">
                            <label for="fecha_ini" class="">Fecha Inicio: </label>
                            <input type="date" class="form-control" id="fecha_ini" name="fecha_ini"
                                value="{{ fecha_ini }}">
                        </div>
                        <div class="form-group ">
                            <label for="fecha_fin" class="">Fecha Fin: </label>
                            <input type="date" class="form-control" id="fecha_fin" name="fecha_fin"
                                value="{{ fecha_fin }}">
                        </div>
                        <div class="form-group ">
                            <label for="plantilla" class="">Plantilla: </label>
                            <select class="form-control" id="plantilla" name="plantilla" required>
                                <option value="" selected disabled>Seleccione</option>
                                {% for plantilla in plantillas %}
                                <option value="{{ plantilla.id }}">{{ plantilla.nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <!--Create 2 columns 1 for parametros and other for puntos-->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group ">
                                    <h5>Parametros</h5>
                                    <div id="check_parametros">

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group ">
                                    <h5>Puntos de medición</h5>
                                    <div id="check_puntos">

                                    </div>
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary my-2">Buscar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>Fechas existentes:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
                <div class="overflow-auto" style="height: 200px;">
                    <ul id="fechas_existentes">
                    </ul>
                </div>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}
{% block javascript %}

<script>
    if ('{{fecha_ini}}' != 'None' && '{{fecha_ini}}' != '') {
        $('#fecha_ini').val('{{fecha_ini}}');
    } else {
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!
        var yyyy = today.getFullYear();

        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        today = yyyy + '-' + mm + '-' + dd;
        $('#fecha_ini').val(today);
    }
    //if fecha_fin from request.get form set value to input else set value to today date at 00:00
    if ('{{fecha_fin}}' != 'None' && '{{fecha_fin}}' != '') {
        $('#fecha_fin').val('{{fecha_fin}}');
    } else {
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!
        var yyyy = today.getFullYear();

        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        today = yyyy + '-' + mm + '-' + dd;
        $('#fecha_fin').val(today);
    }
    //when plantilla change obtain elements thath checkbox input
    $('#plantilla').change(function () {
        //clear checkboxs
        $('#check_parametros').html('');
        $('#check_puntos').html('');
        $('#fechas_existentes').html('');
        var plantilla = $('#plantilla').val();
        $.ajax({
            url: '{% url "reportes:get_form" %}',
            type: 'GET',
            data: {
                plantilla: plantilla
            },
            success: function (data) {
                //iterate over parametros and create checkbox input

                $.each(data.parametros, function (index, parametro) {
                    $('#check_parametros').append(
                        '<div class="form-check">' +
                        '<input class="form-check-input" type="checkbox" value="' +
                        parametro.id +
                        '" id="parametro_' + parametro.id + '" name="parametros" >' +
                        '<label class="form-check-label" for="parametro_' + parametro
                        .id + '">' +
                        parametro.nombre + '</label>' +
                        '</div>'
                    );
                });
                //iterate over puntos and create checkbox input
                $.each(data.puntos, function (index, punto) {
                    $('#check_puntos').append(
                        '<div class="form-check">' +
                        '<input class="form-check-input" type="checkbox" value="' +
                        punto.id +
                        '" id="punto_' + punto.id + '" name="puntos">' +
                        '<label class="form-check-label" for="punto_' + punto
                        .id + '">' +
                        punto.nombre + '</label>' +
                        '</div>'
                    );
                });
                //iterate over fechas and create li element with date
                $.each(data.fechas, function (index, fecha) {
                    $('#fechas_existentes').append(
                        '<li>' + fecha + '</li>'
                    );
                });
            }
        });
    });
</script>
{% endblock javascript %}

templates/reportes/grafico_datos.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'reportes:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver atrás</a>

</div>
<div class="row justify-content-center">
    <div class="col-xl-12 col-md-12 mb-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">ESTADÍSTICAS</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                {% for parametro in parametros  %}
                <h2 class="text-center p-2 mt-3 display-3">{{parametro.nombre}}</h2>
                <div class="row">

                    {% for punto in puntos  %}
                    <div class="col-xl-4 col-md-6 mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <canvas id='jqxChart_{{parametro.id}}_{{punto.id}}'></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</div>
{% endblock contenido %}
{% block javascript %}

<script>
    var datos_json = JSON.parse('{{ datos_json|safe }}');
    //console.log(datos_json)
    //crear multiple graficos de barra 
    //iterar sobre los elementos del json
    for (var key in datos_json) {
        //itera sobre los puntos de cada elemento
        for (var i = 0; i < datos_json[key].length; i++) {
            // console.log(datos_json[key][i])
            const ctx = document.getElementById(`jqxChart_${key}_${datos_json[key][i].id}`).getContext('2d');
            //create chart type line with datos_json[key][i].data
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: datos_json[key][i].data.map(function (e) {
                        return e.fecha
                    }),
                    datasets: [{
                        label: datos_json[key][i].punto,
                        data: datos_json[key][i].data.map(function (e) {
                            return e.valor
                        }),
                        backgroundColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],

                        borderWidth: 1
                    }]
                },

            });

            '{% comment %}'
            /* 
                       var myChart = new Chart(ctx, {
                           type: 'bar',
                           data: {
                               labels: datos_json[key][i].data.map(function (e) {
                                   return e.fecha
                               }),
                               datasets: [{
                                   label: datos_json[key][i].punto,
                                   data: datos_json[key][i].data.map(function (e) {
                                       return e.valor
                                   }),
                                   backgroundColor: [
                                       'rgba(245, 54, 39, 0.8)',
                                       'rgba(12, 24, 233, 0.8)',
                                       'rgba(0, 0, 0, 0.8)',
                                   ],
                                   borderColor: [
                                       'rgba(255, 255, 255, 0.8)',
                                       'rgba(255, 255	, 255, 0.8)',
                                       'rgba(255, 255, 255, 0.8)',
                                   ],
                                   borderWidth: 1

                               }]
                           },
                          
                           options: {
                               responsive: true,
                               scales: {
                                   y: {
                                       ticks: {
                                           beginAtZero: true
                                       }
                                   }
                               }
                           }
                   });*/
            '{% endcomment %}'
        }
    }
</script>
{% endblock javascript %}