CN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400,handler404,handler403,handler500
import debug_toolbar

handler400 = 'CN.views.bad_request'
handler403 = 'CN.views.permission_denied'
handler404 = 'CN.views.page_not_found'
handler500 = 'CN.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.master.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('empresas/', include('apps.empresas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('datos/', include('apps.datos.urls')),
    path('reportes/', include('apps.reportes.urls')),
    path('parametros/', include('apps.parametros.urls')),
    path('puntos_medicion/', include('apps.puntos_medicion.urls')),
    path('plantillas/', include('apps.plantillas.urls')),
    path('licencias/', include('apps.licencias.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/datos/urls.py
from django.urls import  path
from . import views

app_name = "datos"

urlpatterns = [
    path('<int:pk_plantilla>/<str:get_fecha>', views.ingreso_datos, name="ingreso_datos"),
    path('generar_informe/<int:pk_plantilla>/', views.generar_informe, name="generar_informe"),
    path('get_datos/<int:pk_plantilla>/', views.get_datos, name="get_datos"),
    path('agregar_nota/<int:pk_plantilla>/', views.agregar_nota, name="agregar_nota"),
    path('borrar_nota/<int:pk_nota>/', views.borrar_nota, name="borrar_nota"),
    path('borrar_fecha/<int:pk_plantilla>/', views.borrar_fecha, name="borrar_fecha"),
]

apps/empresas/urls.py
from django.urls import  path
from . import views

app_name = "empresas"

urlpatterns = [
    path('', views.ListEmpresas.as_view(), name="index"),
    path('crear', views.CrearEmpresa.as_view(), name="crear"),
    path('editar/<int:pk>', views.EditEmpresa.as_view(), name="editar"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    # path('cargaLogo/<int:pk>',views.CargaLogo, name="cargaLogo"),
    path('cambiar-empresa/<int:pk>',views.cambiarEmpresa, name="cambiarEmpresa"),
]

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index ,name='index'),
    path('menu', views.menu ,name='menu'),
    path('cpu', views.cpu,name='cpu'),
]

apps/parametros/urls.py
from django.urls import  path
from . import views

app_name = "parametros"

urlpatterns = [
    path('', views.ListParametros.as_view(), name="index"),
    path('agregar/', views.CreateParametros.as_view(), name="agregar"),
    path('editar/<int:pk>/', views.EditParametros.as_view(), name="editar"),
    path('predestroy/<int:pk>/', views.predestroy, name="predestroy"),
    path('destroy/<int:pk>/', views.destroy, name="destroy"),
    path('agregar_limite/<int:pk>/', views.agregar_limite, name="agregar_limite"),
]

apps/plantillas/urls.py
from django.urls import  path
from . import views

app_name = "plantillas"

urlpatterns = [
    path('', views.ListPlantillas.as_view(), name="index"),
    path('agregar/', views.CreatePlantilla.as_view(), name="agregar"),
    path('editar/<int:pk>/', views.EditPlantilla.as_view(), name="editar"),
    path('tipos_plantillas/', views.ListTipoPlantilla.as_view(), name="tipos_plantillas"),
    path('tipos_plantillas/agregar/', views.CreateTipoPlantilla.as_view(), name="agregar_tipo_plantilla"),
    path('tipos_plantillas/editar/<int:pk>/', views.EditTipoPlantilla.as_view(), name="editar_tipo_plantilla"),
    path('predestroy_tipo_plantilla/<int:pk>/', views.predestroy_tipo_plantilla, name="predestroy_tipo_plantilla"),
    path('destroy_tipo_plantilla/<int:pk>/', views.destroy_tipo_plantilla, name="destroy_tipo_plantilla"),

]

apps/datos/models.py
from django.db import models
from apps.parametros.models import Parametro
from apps.puntos_medicion.models import PuntoMedicion
from apps.plantillas.models import Plantilla
from apps.usuarios.models import Usuario

# Create your models here.
class Datos(models.Model):
    plantilla = models.ForeignKey(Plantilla, on_delete=models.CASCADE)
    punto_medicion = models.ForeignKey(PuntoMedicion, on_delete=models.CASCADE)
    parametro = models.ForeignKey(Parametro, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    valor = models.FloatField(null=True, blank=True)
    fecha = models.DateField()
    updated = models.DateTimeField(auto_now=True)

class NotasDatos(models.Model):
    plantilla = models.ForeignKey(Plantilla, on_delete=models.CASCADE)
    fecha = models.DateField()
    nota = models.TextField(blank=True,null=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

apps/datos/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import Datos, NotasDatos
from apps.plantillas.models import Plantilla
from apps.parametros.models import Parametro, Limite
from apps.puntos_medicion.models import PuntoMedicion
from datetime import datetime
from django.http import JsonResponse

import json

##############################################################################
@login_required(login_url='/')
def get_datos(request, pk_plantilla):
    """
    Obtiene los datos de una plantilla y los devuelve en formato JSON.
    """
    fecha = request.GET.get('fecha')
    plantilla = Plantilla.objects.get(pk=pk_plantilla)
    datos = Datos.objects.filter(plantilla=plantilla, fecha=fecha)
    notas = NotasDatos.objects.filter(plantilla=plantilla, fecha=fecha)
    datos_json = []
    for dato in datos:
        datos_json.append({
            'id': dato.id,
            'fecha': dato.fecha.strftime('%Y-%m-%d'),
            'valor': dato.valor,
            'punto_medicion': dato.punto_medicion.id,
            'parametro': dato.parametro.id,
            'usuario': dato.usuario.username,
        })
    notas_json = []
    for nota in notas:
        json = {
            'id': nota.id,
            'fecha': nota.fecha.strftime('%Y-%m-%d'),
            'nota': nota.nota,
            'usuario': nota.usuario.username,
        }
        notas_json.append(json)
    return JsonResponse({'datos': datos_json, 'notas': notas_json}, safe=False)
##############################################################################

@login_required(login_url='/')
def agregar_nota(request, pk_plantilla):
    plantilla = Plantilla.objects.get(pk=pk_plantilla)
    fecha = request.GET.get('fecha')
    nota = request.GET.get('nota')
    usuario = request.user
    nota_datos = NotasDatos(plantilla=plantilla, fecha=fecha, nota=nota, usuario=usuario)
    nota_datos.save()
    return JsonResponse({'status': 'ok', 'id': nota_datos.id, 'nota' : nota_datos.nota}, safe=False)

@login_required(login_url='/')
def borrar_nota(request, pk_nota):
    nota = NotasDatos.objects.get(pk=pk_nota)
    plantilla = nota.plantilla.id
    fecha = nota.fecha
    nota.delete()
    return redirect('datos:ingreso_datos', plantilla, fecha)

# Create your views here.
@login_required(login_url="/")
def ingreso_datos(request, pk_plantilla,get_fecha=None):
    if request.method == "GET":
        if get_fecha == None or get_fecha == 'None':
            fecha = datetime.now().date().strftime('%Y-%m-%d')
        else:
            fecha = get_fecha
        plantilla = Plantilla.objects.get(id=pk_plantilla)
        parametros = Parametro.objects.filter(tipo=plantilla.tipo)
        puntos_medicion = PuntoMedicion.objects.filter(empresa=request.user.empresa,tipo=plantilla.tipo)
        datos = Datos.objects.filter(fecha=fecha, plantilla=plantilla)
        fechas_existentes = Datos.objects.filter(plantilla=plantilla).values('fecha').distinct().order_by('fecha')
        notas = NotasDatos.objects.filter(plantilla=plantilla, fecha=fecha)
        context = {
            'plantilla': plantilla,
            'parametros': parametros,
            'puntos_medicion': puntos_medicion,
            'datos': datos,
            'appname': 'Ingreso de datos',
            'fecha' : fecha,
            'fechas_existentes': fechas_existentes,
            'notas': notas,
        }
        return render(request, "datos/ingreso_datos.html", context)
    elif request.method == "POST":
        plantilla = Plantilla.objects.get(id=pk_plantilla)
        #request.post csrf_token + punto_medicion.id_parametro.id_parametro destructured
        fecha_dato = request.POST['fecha']
        for values in request.POST:
            # print(values)
            #skip ['csrfmiddlewaretoken'] and ['']
            if 'csrfmiddlewaretoken' not in values and 'fecha' not in values and 'text_notas' not in values:
                #separate id_parametro and id_punto_medicion by underscore
                list = values.split("_")
                id_punto_medicion = list[0]
                id_parametro  = list[1]
                #get id_punto_medicion and id_parametro
                punto_medicion = PuntoMedicion.objects.get(id=id_punto_medicion)
                parametro = Parametro.objects.get(id=id_parametro)
                #get value 
                valor = request.POST[str(punto_medicion.id) + "_" + str(parametro.id)]
                if valor == "":
                    valor = 0
                #if valor format is 20,0 then convert to float
                try:
                    if valor.count(",") == 1:
                        valor = valor.replace(",", ".")
                        valor = float(valor)
                except:
                    pass
                #update or create datos if exist data with date and plantilla
                try:
                    datos = Datos.objects.get(fecha=fecha_dato, plantilla=plantilla, punto_medicion=punto_medicion, parametro=parametro)
                except Datos.DoesNotExist:
                    datos = Datos.objects.create(punto_medicion=punto_medicion, parametro=parametro, valor=valor, plantilla=plantilla, usuario=request.user, fecha=fecha_dato)
                #if valor of datos is equal to valor then do nothing, else update datos and user
                if float(datos.valor) == valor:
                    pass
                else:
                    datos.valor = valor
                    datos.usuario = request.user
                    datos.save()
        messages.success(request, "Datos ingresados correctamente")            
        return redirect('datos:ingreso_datos', pk_plantilla=plantilla.id, get_fecha=None)
    else:
        return redirect('datos:ingreso_datos', pk_plantilla=plantilla.id,get_fecha=None)

@login_required(login_url="/")
def generar_informe(request, pk_plantilla):
    if request.method == "GET":
        plantilla = Plantilla.objects.get(id=pk_plantilla)
        puntos = PuntoMedicion.objects.filter(tipo=plantilla.tipo, empresa=request.user.empresa)
        parametros = Parametro.objects.filter(tipo=plantilla.tipo)
        #obtain group by fecha, parametros and puntos of datos of plantilla
        fechas_existentes = Datos.objects.filter(plantilla=plantilla).values('fecha').distinct().order_by('fecha')
        puntos_list = []
        parametros_list = []
        for punto in puntos:
            puntos_list.append({
                'nombre' : punto.nombre,
                'id' : punto.id,
            })
        for parametro in parametros:
            parametros_list.append({
                'nombre' : parametro.nombre,
                'id' : parametro.id,
            })
        #convert all datos to float
        context = {
            'plantilla': plantilla,
            'appname': 'Generar informe',
            'puntos': puntos_list,
            'parametros': parametros_list,
            'fechas_existentes': fechas_existentes,
        }
        return render(request, "datos/generar_informe.html", context)
    elif request.method == "POST":
        fecha_ini_tabla = request.POST['fecha_ini_tabla']
        fecha_ini = request.POST['fecha_ini']
        fecha_fin = request.POST['fecha_fin']
        plantilla = Plantilla.objects.get(id=pk_plantilla)
        puntos_form = request.POST.getlist('puntos')
        parametros_form = request.POST.getlist('parametros')
        if plantilla.tipo.nombre == "caldera":
            #obtain all datos with plantilla
            datos = Datos.objects.filter(plantilla=plantilla,fecha=fecha_ini_tabla)
            if datos.count() == 0:
                messages.success(request, 'No hay datos para la fecha seleccionada.',extra_tags='danger')
                return redirect('datos:generar_informe', pk_plantilla=plantilla.id)
            json_data = []
            try:
                #obtain all valores from datos when parametro contains "conductividad"
                conductividad = datos.filter(parametro__nombre__icontains="conductividad")
                #count all puntos_medicion from conductividad when nombre contains "caldera"
                calderas = conductividad.filter(Q(punto_medicion__nombre__icontains="caldera") | Q(punto_medicion__nombre__icontains="autoclave"))
                alimentacion = conductividad.get(punto_medicion__nombre__icontains="alimentacion")
                factor_conductividad = {"name": "Factor de conductividad", "data": []}
                for caldera in calderas:
                    factor_conductividad["data"].append({"name": caldera.punto_medicion.nombre, "valor": round(caldera.valor/alimentacion.valor, 2)})
                json_data.append(factor_conductividad)
                cloruros = datos.filter(parametro__nombre__icontains="cloruros")
                calderas = cloruros.filter(Q(punto_medicion__nombre__icontains="caldera") | Q(punto_medicion__nombre__icontains="autoclave"))
                alimentacion = cloruros.get(punto_medicion__nombre__icontains="alimentacion")
                factor_clorus = {"name": "Factor de cloruros", "data": []}
                for caldera in calderas:
                    factor_clorus["data"].append({"name": caldera.punto_medicion.nombre, "valor": round(caldera.valor/alimentacion.valor, 2)})
                json_data.append(factor_clorus)
                silice = datos.filter(parametro__nombre__icontains="silice")
                calderas = silice.filter(Q(punto_medicion__nombre__icontains="caldera") | Q(punto_medicion__nombre__icontains="autoclave"))
                alimentacion = silice.get(punto_medicion__nombre__icontains="alimentacion")
                factor_silice = {"name": "Factor de silice", "data": []}
                for caldera in calderas:

templates/datos/datos_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    {% if fecha_dato is false %}
    <a href="{% url 'datos:agregar' %}" class="align-self-center ms-2 mb-1 btn btn-success text-light border"><i
            class="fas fa-plus-circle"></i> Agregar Datos</a>
    {% endif %}
</div>
<div class="table-responsive mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>Valor 1</th>
                <th>Valor 2</th>
                <th>Valor 3</th>
                <th>Fecha</th>
                <th>Usuario</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for datos in object_list %}
            <tr>
                <td>{{datos.valor1}}</td>
                <td>{{datos.valor2}}</td>
                <td>{{datos.valor3}}</td>
                <td>{{datos.fecha}}</td>
                <td>{{datos.usuario.first_name}} {{datos.usuario.last_name}}</td>
                <td>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'datos:editar' pk=datos.id %}" id="edit"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock contenido %}
{% block javascript %}
<script>
</script>
{% endblock javascript %}

templates/datos/ingreso_datos.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'plantillas:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver atrás</a>
</div>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<!--FECHA HOY-->
<!--- create form with horizontal is {{puntos_medicion}} and vertical is {{parametros}}-->
<button type="button" class="btn btn-primary mb-4" data-bs-toggle="modal" data-bs-target="#modal">
    Fechas Existentes
</button>
<div class="card shadow mb-4">

    <div class="card-body">
        <form action="{% url 'datos:ingreso_datos' pk_plantilla=plantilla.id get_fecha=None %}" method="POST">
            {% csrf_token %}
            <div class="form-group col-xl-4">
                <label for="fecha">Fecha </label>
                <input type="date" class="form-control" id="fecha" name="fecha" value="{{fecha}}"
                    max="{% now "Y-m-d" %}" required>
            </div>

            <!--horizontal is bucle ti {{puntos_medicion}}-->
            <table class="table table-bordered table-responsive-xl justify-content-center">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">#</th>
                        {% for punto_medicion in puntos_medicion %}
                        <th scope="col">{{punto_medicion.nombre}}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    <!--vertical is bucle ti {{parametros}}-->
                    {% for parametro in parametros %}
                    <tr>
                        <th scope="row">{{parametro.nombre}}</th>
                        {% for punto_medicion in puntos_medicion %}
                        <td>
                            <input type="text" class="form-control value" name="{{punto_medicion.id}}_{{parametro.id}}"
                                id="{{punto_medicion.id}}_{{parametro.id}}" placeholder="Ingrese valor">
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="my-4">
                <label for="text_notas">Agregar analisis de datos:</label>
                <textarea class="form-control" name="text_notas" id="text_notas" cols="30" rows="5"></textarea>
                <button id="agregar_nota" class="btn btn-primary mt-2 float-end">Agregar</button>
            </div>
            <div>
                <ul id="notas">
                    {% for nota in notas  %}
                    <li id="{{nota.id}}">{{nota.nota}} - <a href="{% url 'datos:borrar_nota' pk_nota=nota.id %}">
                            <small>Eliminar</small></a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <!--button submit in center-->
            <div class=" text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

        </form>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>Fechas existentes:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
                <div class="overflow-auto" style="height: 200px;">
                    <ul>
                        {% for fecha in fechas_existentes %}
                        <li class="text-right mb-1" id="{{fecha.fecha|date:'Y-m-d'}}">{{fecha.fecha}} <a href=""
                                elem="{{fecha.fecha|date:'Y-m-d'}}"
                                class="badge bg-danger text-decoration-none text-light fechas_existentes">Eliminar</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}
{% block javascript %}
<script>
    //with {{datos}} populate the table with the data 

    '{% for dato in datos %}'
    //'{{dato.valor}}' format 20,0 to 20.0
    $('#{{dato.punto_medicion.id}}_{{dato.parametro.id}}').val('{{dato.valor|floatformat:2}}');
    //add <small> to every input with dato.usuario
    $('#{{dato.punto_medicion.id}}_{{dato.parametro.id}}').after('<small>{{dato.usuario}}</small>');

    '{% endfor %}'

    //if fecha change, get the data from the server and populate the table:
    $('#fecha').change(function () {
        $('#notas').empty();
        var fecha = $('#fecha').val();
        var url = '{% url "datos:get_datos" pk_plantilla=plantilla.id %}';
        $.ajax({
            url: url,
            type: 'GET',
            data: {
                fecha: fecha
            },
            success: function (data) {
                //if data is empty values
                if (data['datos'].length == 0) {
                    $('.value').val('');
                    $('small').remove();
                }
                //with data populate the table with the data
                for (var i = 0; i < data['datos'].length; i++) {
                    $('#' + data['datos'][i].punto_medicion + '_' + data['datos'][i].parametro).val(
                        data['datos'][i]
                        .valor);
                    //remove the <small> and add it again with the new user
                    $('#' + data['datos'][i].punto_medicion + '_' + data['datos'][i].parametro)
                        .next().remove();
                    $('#' + data['datos'][i].punto_medicion + '_' + data['datos'][i].parametro)
                        .after(
                            '<small>' + data['datos'][i].usuario + '</small>');
                }
                //add notas from data['notas']
                for (var i = 0; i < data['notas'].length; i++) {
                    $('#notas').append('<li id=' + data['notas'][i].id + '>' + data['notas'][i]
                        .nota +
                        '- <a href="/datos/borrar_nota/' + data['notas'][i].id +
                        '"> <small>Eliminar</small></a> </li>'
                    );

                }
            }
        });
    });

    //if the user click on the button add_nota, add the textarea to the ul
    $('#agregar_nota').click(function () {
        //prevent default
        event.preventDefault();
        $.ajax({
            url: '{% url "datos:agregar_nota" pk_plantilla=plantilla.id %}',
            type: 'GET',
            data: {
                nota: $('#text_notas').val(),
                fecha: $('#fecha').val()
            },
            success: function (data) {
                $('#notas').append('<li id=' + data.id + '>' + data.nota +
                    '- <a href="/datos/borrar_nota/' + data.id +
                    '"> <small>Eliminar</small></a> </li>'
                );

            }
        });
        $('#text_notas').val('');
    });

    //if the user click on the button in class fechas_existentes, delete the fecha via post
    $('.fechas_existentes').click(function () {
        //prevent default
        event.preventDefault();
        var fecha = $(this).attr('elem');
        $.ajax({
            url: '{% url "datos:borrar_fecha" pk_plantilla=plantilla.id %}',
            type: 'POST',
            data: {
                fecha: fecha,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function (data) {
                //if status is ok remove the li
                if (data.status == 'ok') {
                    $('#' + fecha).remove();
                }
            }
        });
    });
</script>
{% endblock javascript %}