CN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400,handler404,handler403,handler500
import debug_toolbar

handler400 = 'CN.views.bad_request'
handler403 = 'CN.views.permission_denied'
handler404 = 'CN.views.page_not_found'
handler500 = 'CN.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.master.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('empresas/', include('apps.empresas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('datos/', include('apps.datos.urls')),
    path('reportes/', include('apps.reportes.urls')),
    path('parametros/', include('apps.parametros.urls')),
    path('puntos_medicion/', include('apps.puntos_medicion.urls')),
    path('plantillas/', include('apps.plantillas.urls')),
    path('licencias/', include('apps.licencias.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/empresas/urls.py
from django.urls import  path
from . import views

app_name = "empresas"

urlpatterns = [
    path('', views.ListEmpresas.as_view(), name="index"),
    path('crear', views.CrearEmpresa.as_view(), name="crear"),
    path('editar/<int:pk>', views.EditEmpresa.as_view(), name="editar"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    # path('cargaLogo/<int:pk>',views.CargaLogo, name="cargaLogo"),
    path('cambiar-empresa/<int:pk>',views.cambiarEmpresa, name="cambiarEmpresa"),
]

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index ,name='index'),
    path('menu', views.menu ,name='menu'),
    path('cpu', views.cpu,name='cpu'),
]

apps/reportes/urls.py
from django.urls import  path
from . import views

app_name = "reportes"

urlpatterns = [
    path('', views.index, name="index"),
    path('get_form/', views.get_form, name="get_form"),
    path('get_datos/', views.get_datos, name="get_datos"),
]

apps/usuarios/urls.py
from django.urls import  path
from .formularios import UserLoginForm
from . import views

app_name = "usuarios"

urlpatterns = [
    path('',views.ListUsuarios.as_view(), name='index'),
    path('registrar', views.Registrar.as_view(), name="registrar"),
    path('login',views.Login.as_view(authentication_form=UserLoginForm),name='login'),
    path('perfil/<int:pk>',views.Profile.as_view(),name='perfil'),
    path('crear',views.CreateUsuario.as_view(),name='crear'),
    path('editar/<int:pk>',views.EditUsuario.as_view(),name='editar'),
    path('predestroy/<int:pk>',views.predestroy,name='predestroy'),
    path('destroy/<int:pk>',views.destroy,name='destroy'),
]

templates/canvas.html
<script>
    var datos_json = JSON.parse('{{ datos_json|safe }}');
    for (var key in datos_json) {
        for (var i = 0; i < datos_json[key].length; i++) {
            console.log(datos_json[key][i])
            const ctx = document.getElementById(`jqxChart_${key}_${datos_json[key][i].id}`).getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: datos_json[key][i].data.map(function (e) {
                        return e.fecha
                    }),
                    datasets: [{
                        label: datos_json[key][i].punto,
                        data: datos_json[key][i].data.map(function (e) {
                            return e.valor
                        }),
                        backgroundColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],

                        borderWidth: 1
                    }]
                },

            });
        }
    }
</script>
{% for parametro in parametros_list  %}
<h2>{{parametro.nombre}}</h2>
<div>
    {% for punto in puntos_list  %}
    <div>
        <canvas id='jqxChart_{{parametro.id}}_{{punto.id}}'></canvas>
    </div>
    {% endfor %}

</div>
{% endfor %}

templates/errors.html
<!DOCTYPE html>
<html lang="en" class="">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <!-- Icono Navegador -->
    <link rel="shortcut icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <!-- Fin  -->
    <!-- Fin Icono Navegador -->
    <link rel="stylesheet" href="{% static 'master/css/style_404.css' %}">
    <link rel="stylesheet" href="{% block styles %}{% endblock styles %}">
    <!-- Fin  -->
    <title class="edit_appname">{{code}}</title>
</head>

<body>
    <div class="moon"></div>
    <div class="moon__crater moon__crater1"></div>
    <div class="moon__crater moon__crater2"></div>
    <div class="moon__crater moon__crater3"></div>

    <div class="star star1"></div>
    <div class="star star2"></div>
    <div class="star star3"></div>
    <div class="star star4"></div>
    <div class="star star5"></div>

    <div class="error">
        <div class="error__title">{{code}}</div>
        <div class="error__subtitle">Hmmm...</div>
        <div class="error__description">Parece que uno de los desarrolladores se quedó dormido</div>
        <a class="error__button error__button--active" href="{% url 'master:index' %}">Home</a>
        <a class="error__button" href="https://www.telectronic.com">Contacto</a>
    </div>

    <div class="astronaut">
        <div class="astronaut__backpack"></div>
        <div class="astronaut__body"></div>
        <div class="astronaut__body__chest"></div>
        <div class="astronaut__arm-left1"></div>
        <div class="astronaut__arm-left2"></div>
        <div class="astronaut__arm-right1"></div>
        <div class="astronaut__arm-right2"></div>
        <div class="astronaut__arm-thumb-left"></div>
        <div class="astronaut__arm-thumb-right"></div>
        <div class="astronaut__leg-left"></div>
        <div class="astronaut__leg-right"></div>
        <div class="astronaut__foot-left"></div>
        <div class="astronaut__foot-right"></div>
        <div class="astronaut__wrist-left"></div>
        <div class="astronaut__wrist-right"></div>

        <div class="astronaut__cord">
            <canvas id="cord" height="500px" width="500px"></canvas>
        </div>

        <div class="astronaut__head">
            <canvas id="visor" width="60px" height="60px"></canvas>
            <div class="astronaut__head-visor-flare1"></div>
            <div class="astronaut__head-visor-flare2"></div>
        </div>
    </div>
    <script>
        function drawVisor() {
            const canvas = document.getElementById('visor');
            const ctx = canvas.getContext('2d');

            ctx.beginPath();
            ctx.moveTo(5, 45);
            ctx.bezierCurveTo(15, 64, 45, 64, 55, 45);

            ctx.lineTo(55, 20);
            ctx.bezierCurveTo(55, 15, 50, 10, 45, 10);

            ctx.lineTo(15, 10);

            ctx.bezierCurveTo(15, 10, 5, 10, 5, 20);
            ctx.lineTo(5, 45);

            ctx.fillStyle = '#2f3640';
            ctx.strokeStyle = '#f5f6fa';
            ctx.fill();
            ctx.stroke();
        }

        const cordCanvas = document.getElementById('cord');
        const ctx = cordCanvas.getContext('2d');

        let y1 = 160;
        let y2 = 100;
        let y3 = 100;

        let y1Forward = true;
        let y2Forward = false;
        let y3Forward = true;

        function animate() {
            requestAnimationFrame(animate);
            ctx.clearRect(0, 0, innerWidth, innerHeight);

            ctx.beginPath();
            ctx.moveTo(130, 170);
            ctx.bezierCurveTo(250, y1, 345, y2, 400, y3);

            ctx.strokeStyle = 'white';
            ctx.lineWidth = 8;
            ctx.stroke();


            if (y1 === 100) {
                y1Forward = true;
            }

            if (y1 === 300) {
                y1Forward = false;
            }

            if (y2 === 100) {
                y2Forward = true;
            }

            if (y2 === 310) {
                y2Forward = false;
            }

            if (y3 === 100) {
                y3Forward = true;
            }

            if (y3 === 317) {
                y3Forward = false;
            }

            y1Forward ? y1 += 1 : y1 -= 1;
            y2Forward ? y2 += 1 : y2 -= 1;
            y3Forward ? y3 += 1 : y3 -= 1;
        }

        drawVisor();
        animate();
    </script>
</body>

templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="row">
    <div class="col-xl-3 col-md-6 mb-4" id="llamadas_ingresadas">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">CANTIDAD USUARIOS</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            {{usuarios}}
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users-cog fa-2x text-gray-300"></i>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4" id="llamadas_contestadas">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">CANTIDAD </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">0
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-phone fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4" id="llamadas_abandonadas">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary  mb-1">CANTIDAD </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">0
                        </div>
                    </div>
                    <div class="col-auto">

                        <i class="fas fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4" id="llamadas_outbound">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary  mb-1">CANTIDAD
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">0

                        </div>
                    </div>
                    <div class="col-auto">

                        <i class="far fa-bookmark fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-6 col-lg-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Memoria RAM</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div id='chartmemoriaram' style="width: 100%; height: 180px;"></div>
            </div>
        </div>
    </div>

    <div class="col-xl-6 col-lg-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">HDD</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div id="charthdd" style="width: 100%; height: 180px;"></div>
            </div>
        </div>
    </div>

    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">CPU</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div id="chartCpu" style="width: 100%; height: 300px;"></div>
            </div>
        </div>
    </div>

</div>
{% endblock contenido %}
{% block javascript %}

<script>
    var data = [{
            valor: "{{ramUsage}}",
            nombre: "Usado"
        },
        {
            valor: "{{ramAvailable}}",
            nombre: "Restante"
        }
    ];

    $(document).ready(function () {

        var dataAdapter = new $.jqx.dataAdapter(data, {
            async: false,
            autoBind: true,
            loadError: function (xhr, status, error) {
                alert('Error loading "' + source.url + '" : ' + error);
            }
        });
        $.jqx._jqxChart.prototype.colorSchemes.push({
            name: 'myScheme',
            colors: ['#FF5733', '#2980B9']
        });
        // prepare jqxChart settings
        var settings = {
            title: "",
            description: "",
            enableAnimations: true,
            showLegend: true,
            showBorderLine: true,
            legendLayout: {
                left: 050,
                top: 100,
                width: 100,
                height: 80,
                flow: 'vertical'
            },
            padding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0
            },
            titlePadding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0
            },
            source: dataAdapter,
            colorScheme: 'myScheme',
            seriesGroups: [{
                type: 'pie',
                showLabels: true,
                series: [{
                    dataField: 'valor',
                    displayText: 'nombre',
                    labelRadius: 100,
                    initialAngle: 10,
                    radius: 80,
                    centerOffset: 0,
                    formatFunction: function (value) {
                        if (isNaN(value))
                            return value;
                        return parseInt(value) + '%';
                    },
                }]
            }]
        };
        // setup the chart
        $('#chartmemoriaram').jqxChart(settings);
    });




    var data2 = [{
            valor: "{{hddUsage}}",
            nombre: "Usado"
        },
        {
            valor: "{{hddAvailable}}",
            nombre: "Restante"
        }

    ];
    $(document).ready(function () {

        var dataAdapter = new $.jqx.dataAdapter(data2, {
            async: false,
            autoBind: true,
            loadError: function (xhr, status, error) {
                alert('Error loading "' + source.url + '" : ' + error);
            }
        });
        $.jqx._jqxChart.prototype.colorSchemes.push({
            name: 'myScheme2',
            colors: ['#FF5733', '#2980B9']
        });
        // prepare jqxChart settings
        var settings2 = {
            title: "",
            description: "",
            enableAnimations: true,
            showLegend: true,
            showBorderLine: true,
            legendLayout: {
                left: 050,
                top: 100,
                width: 100,
                height: 80,
                flow: 'vertical'
            },
            padding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0
            },
            titlePadding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0
            },
            source: dataAdapter,
            colorScheme: 'myScheme2',
            seriesGroups: [{
                type: 'pie',
                showLabels: true,
                series: [{
                    dataField: 'valor',
                    displayText: 'nombre',
                    labelRadius: 100,
                    initialAngle: 10,
                    radius: 80,
                    centerOffset: 0,
                    formatFunction: function (value) {
                        if (isNaN(value))
                            return value;
                        return parseFloat(value) + 'G';
                    },
                }]
            }]
        };
        // setup the chart
        $('#charthdd').jqxChart(settings2);
    });


    $(document).ready(function () {

        var data = [];
        var max = 100;
        var timestamp = new Date();
        for (var i = 0; i < 60; i++) {
            timestamp.setMilliseconds(0);
            timestamp.setSeconds(timestamp.getSeconds() - 1);
            data.push({
                timestamp: new Date(timestamp.valueOf()),
                value: Math.max(100, (Math.random() * 1000) % max)
            });
        }
        data = data.reverse();
        var settings = {
            title: "Uso % CPU en tiempo real",
            description: " ",
            enableAnimations: false,
            animationDuration: 1000,
            enableAxisTextAnimation: true,
            showLegend: true,

            source: data,
            xAxis: {
                dataField: 'timestamp',
                type: 'date',
                baseUnit: 'second',
                //unitInterval: 5,
                formatFunction: function (value) {
                    return $.jqx.dataFormat.formatdate(value, "hh:mm:ss", 'en-us');
                },
                gridLines: {
                    step: 2
                },
                valuesOnTicks: true,
                labels: {
                    angle: -45,
                    offset: {
                        x: -17,
                        y: 0
                    }
                }
            },
            colorScheme: 'scheme03',
            seriesGroups: [{
                type: 'line',
                columnsGapPercent: 50,
                alignEndPointsWithIntervals: true,
                valueAxis: {
                    //minValue: 0,
                    //maxValue: 1000,
                    title: {
                        text: 'Porcentaje'
                    }
                },
                series: [{
                    dataField: 'value',
                    displayText: 'Usabilidad',
                    opacity: 1,
                    lineWidth: 2,
                    symbolType: 'circle',
                    fillColorSymbolSelected: 'white',
                    symbolSize: 4
                }]
            }]
        };
        // create the chart
        $('#chartCpu').jqxChart(settings);

        // auto update timer
        var ttimer = setInterval(function () {
            $.ajax({
                type: "GET",
                url: "{% url 'master:cpu' %}",
                dataType: "json",
                success: function (output) {
                    value1 = output["cpu"]
                    var max = 100;
                    if (data.length >= 60)
                        data.splice(0, 1);
                    var timestamp = new Date();
                    timestamp.setSeconds(timestamp.getSeconds());
                    timestamp.setMilliseconds(0);
                    data.push({
                        timestamp: timestamp,
                        value: value1
                    });
                    $('#chartCpu').jqxChart('update');
                }
            });
        }, 1000);
    });
</script>

{% endblock javascript %}

templates/sidebar.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-corus-sidebar sidebar sidebar-dark accordion fs-3 text" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center m-1" href="/">

        <div class="sidebar-brand-text mx-3">
            <img width="100%" src="{% static 'master/img/logo.jpg' %}" alt="Logo">
        </div>

    </a>

    {% comment %}
    <!-- Nav Item - Dashboard -->
    <li id="nav-dashboard" class="nav-item ">
        <a class="nav-link" href="/">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li> {% endcomment %}

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        General
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    {% if user.is_superuser %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'licencias:generar_licencia' %}">
            <i class="fas fa-fw fa-key"></i>
            <span>Generar Licencia</span>
        </a>
    </li>
    {% endif %}
    {% if user.is_superuser %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'plantillas:tipos_plantillas' %}">
            <i class="fas fa-fw fa-file-alt"></i>
            <span>Tipo Plantilla</span>
        </a>
    </li>
    {% endif %}

    {% if user.is_staff  %}
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-bs-toggle="collapse"
            data-bs-target="#collapseSA" aria-expanded="false" aria-controls="collapseSA">
            <i class="fas fa-brain"></i>
            <span>Admin</span>
        </a>
        <div id="collapseSA" class="accordion-collapse collapse" aria-labelledby="headingOne"
            data-bs-parent="#accordionSidebar">
            <div class="bg-white py-2 font-weight-bold collapse-inner rounded">
                <a id="nav-usuarios" class="collapse-item font-weight-bold"
                    href="{% url 'usuarios:index' %}">Usuarios</a>
                <a id="nav-licencias" class="collapse-item font-weight-bold"
                    href="{% url 'licencias:index' %}">Licencias</a>
                <a id="nav-empresas" class="collapse-item font-weight-bold"
                    href="{% url 'empresas:index' %}">Empresas</a>
                <a id="nav-parámetros" class="collapse-item font-weight-bold"
                    href="{% url 'parametros:index' %}">Parámetros</a>
                <a id="nav-puntos_medición" class="collapse-item font-weight-bold"
                    href="{% url 'puntos_medicion:index' %}">Puntos de Medición</a>
            </div>
        </div>
    </li>
    {% endif %}

    <li class="nav-item">
        <a class="nav-link" href="{% url 'plantillas:index' %}">
            <i class="fas fa-fw fa-file"></i>
            <span>Plantillas</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'reportes:index' %}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Gráficos</span></a>
    </li>

    <!-- Sidebar Toggler (Sidebar) -->
    <hr class="sidebar-divider d-none d-md-block">

    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
{% block javascript %}

{% endblock javascript %}

templates/topbar.html
{% load static %}
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <div class="d-sm-flex align-items-center justify-content-between ">
        <h1 id="edit_appname" class="h4 mb-0 text-danger edit_appname">{{appname|upper}}</h1>
    </div>
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - User Information -->

        <li class="nav-item dropdown no-arrow">
            <a class="nav-link disabled text-dark">{{user.empresa.nombre}}</a>
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle  " href="#" id="navbarDropdownMenuLink" role="button"
                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Bienvenido {{user.first_name}}</span>
                <img class="img-profile rounded-circle" src="{% static 'master/img/icono.jpg' %}">
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'usuarios:perfil' pk=user.id %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Perfil
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Cerrar Sesión
                </a>
            </div>
        </li>
    </ul>
</nav>

<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Confirma?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body-logout ms-4 p-3">Estás seguro que quieres finalizar sesión?.</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <a class="btn btn-danger" href="{% url 'logout' %}">Salir</a>
            </div>
        </div>
    </div>
</div>