CN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400,handler404,handler403,handler500
import debug_toolbar

handler400 = 'CN.views.bad_request'
handler403 = 'CN.views.permission_denied'
handler404 = 'CN.views.page_not_found'
handler500 = 'CN.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.master.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('empresas/', include('apps.empresas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('datos/', include('apps.datos.urls')),
    path('reportes/', include('apps.reportes.urls')),
    path('parametros/', include('apps.parametros.urls')),
    path('puntos_medicion/', include('apps.puntos_medicion.urls')),
    path('plantillas/', include('apps.plantillas.urls')),
    path('licencias/', include('apps.licencias.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/datos/urls.py
from django.urls import  path
from . import views

app_name = "datos"

urlpatterns = [
    path('<int:pk_plantilla>/<str:get_fecha>', views.ingreso_datos, name="ingreso_datos"),
    path('generar_informe/<int:pk_plantilla>/', views.generar_informe, name="generar_informe"),
    path('get_datos/<int:pk_plantilla>/', views.get_datos, name="get_datos"),
    path('agregar_nota/<int:pk_plantilla>/', views.agregar_nota, name="agregar_nota"),
    path('borrar_nota/<int:pk_nota>/', views.borrar_nota, name="borrar_nota"),
    path('borrar_fecha/<int:pk_plantilla>/', views.borrar_fecha, name="borrar_fecha"),
]

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index ,name='index'),
    path('menu', views.menu ,name='menu'),
    path('cpu', views.cpu,name='cpu'),
]

apps/plantillas/urls.py
from django.urls import  path
from . import views

app_name = "plantillas"

urlpatterns = [
    path('', views.ListPlantillas.as_view(), name="index"),
    path('agregar/', views.CreatePlantilla.as_view(), name="agregar"),
    path('editar/<int:pk>/', views.EditPlantilla.as_view(), name="editar"),
    path('tipos_plantillas/', views.ListTipoPlantilla.as_view(), name="tipos_plantillas"),
    path('tipos_plantillas/agregar/', views.CreateTipoPlantilla.as_view(), name="agregar_tipo_plantilla"),
    path('tipos_plantillas/editar/<int:pk>/', views.EditTipoPlantilla.as_view(), name="editar_tipo_plantilla"),
    path('predestroy_tipo_plantilla/<int:pk>/', views.predestroy_tipo_plantilla, name="predestroy_tipo_plantilla"),
    path('destroy_tipo_plantilla/<int:pk>/', views.destroy_tipo_plantilla, name="destroy_tipo_plantilla"),

]

apps/plantillas/models.py
from django.db import models
from apps.empresas.models import Empresa

# Create your models here.
class TipoPlantilla(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

class Plantilla(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="plantillas_empresa")
    nombre = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)
    tipo = models.ForeignKey(TipoPlantilla, on_delete=models.CASCADE, related_name="plantillas_tipo")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()
        super().save(*args, **kwargs)

apps/plantillas/views.py
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Plantilla, TipoPlantilla
from .formularios import FormularioPlantilla,FormularioTipoPlantilla
from datetime import date, datetime
from django.http import JsonResponse

@method_decorator(login_required, name='dispatch')
class ListPlantillas(ListView):
    model = Plantilla
    template_name = "plantillas/plantillas_list.html"

    def get_queryset(self):
        queryset = Plantilla.objects.filter(empresa=self.request.user.empresa)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListPlantillas, self).get_context_data(**kwargs)
        context['appname'] = "plantillas"
        return context

        
@method_decorator(login_required, name='dispatch')
class CreatePlantilla(CreateView):
    model = Plantilla
    form_class = FormularioPlantilla
    template_name = "formularios/generico.html"
    success_url = reverse_lazy('plantillas:index')

    def get_context_data(self, **kwargs):
        context = super(CreatePlantilla, self).get_context_data(**kwargs)
        context['appname'] = "plantillas"
        return context

    def form_valid(self, form):
        form.instance.empresa = self.request.user.empresa
        return super(CreatePlantilla, self).form_valid(form)


    def get_form_kwargs(self):
        kwargs = super(CreatePlantilla, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get(self, *args, **kwargs):
        if self.request.user.is_staff:
            return super().get(*args, **kwargs)
        return redirect("master:index")

        
@method_decorator(login_required, name='dispatch')
class EditPlantilla(UpdateView):
    template_name = "formularios/generico.html"
    model = Plantilla
    form_class = FormularioPlantilla
    success_url = reverse_lazy("plantillas:index")

    def get_context_data(self, **kwargs):
        context = super(EditPlantilla, self).get_context_data(**kwargs)
        context['legend'] = f"Editar Plantilla"
        context['appname'] = "plantillas"
        return context
    
    def get_form_kwargs(self):
        kwargs = super(EditPlantilla, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get(self, request, pk):
        objeto = self.get_object()
        if self.request.user.empresa != objeto.empresa:
            return redirect("master:index")
        elif not self.request.user.is_staff:
            return redirect("master:index")
        return super().get(request)


# @login_required(login_url="/")
# def predestroy(request, pk):
#     if request.user.has_perm('asterisk.delete_siptrunk'):
#         if request.method == "GET":
#             try:
#                 siptrunk = SipTrunk.objects.get(id=pk)
#             except:
#                 return redirect("siptrunk:index")
#             context={
#                 'id' : siptrunk.id,
#                 'troncal': siptrunk.troncal,
#                 'host': siptrunk.host,
#             }
#             return JsonResponse(context)
#     return redirect("siptrunk:index")

# @login_required(login_url="/")
# def destroy(request,pk):
#     if request.user.has_perm('asterisk.delete_siptrunk'):
#         if request.method == "GET":
#             try:
#                 siptrunk = SipTrunk.objects.get(id=pk)
#             except:
#                 return redirect("siptrunk:index")
#             if request.user.empresa == siptrunk.empresa:
#                 try:
#                     config = configparser.ConfigParser()
#                     with open(sip_custom, 'r+') as s:
#                         config.read_file(s)
#                         config.remove_section(siptrunk.troncal)
#                         s.seek(0)
#                         config.write(s)
#                         s.truncate()
#                     siptrunk.delete()
#                     cmd = "rasterisk -x \"sip reload\""
#                     os.system(cmd)
#                 except:
#                     messages.success(request,f'No se puede eliminar elemento ya que tiene elementos asignados',extra_tags='danger')
#     return redirect("siptrunk:index")

@method_decorator(login_required, name='dispatch')
class ListTipoPlantilla(ListView):
    model = TipoPlantilla
    template_name = "plantillas/tipo_plantilla_list.html"

    def get_context_data(self, **kwargs):
        context = super(ListTipoPlantilla, self).get_context_data(**kwargs)
        context['appname'] = "plantillas"
        return context
    
    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        return redirect("master:index")

@method_decorator(login_required, name='dispatch')
class CreateTipoPlantilla(CreateView):
    model = TipoPlantilla
    form_class = FormularioTipoPlantilla
    template_name = "formularios/generico.html"
    success_url = reverse_lazy('plantillas:tipos_plantillas')

    def get_context_data(self, **kwargs):
        context = super(CreateTipoPlantilla, self).get_context_data(**kwargs)
        context['appname'] = "plantillas"
        return context

    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        return redirect("master:index")

@method_decorator(login_required, name='dispatch')
class EditTipoPlantilla(UpdateView):
    model = TipoPlantilla
    form_class = FormularioTipoPlantilla
    template_name = "formularios/generico.html"
    success_url = reverse_lazy("plantillas:tipos_plantillas")

    def get_context_data(self, **kwargs):
        context = super(EditTipoPlantilla, self).get_context_data(**kwargs)
        context['appname'] = "plantillas"
        return context

    def get(self, request, pk):
        if self.request.user.is_superuser:
            return super().get(request)
        return redirect("master:index")

@login_required(login_url="/")
def predestroy_tipo_plantilla(request, pk):
    if request.method == "GET":
        try:
            tipo_plantilla = TipoPlantilla.objects.get(id=pk)
        except:
            return redirect("plantillas:tipos_plantillas")
        context={
            'id' : tipo_plantilla.id,
            'nombre': tipo_plantilla.nombre,
        }
        return JsonResponse(context)
    return redirect("plantillas:tipos_plantillas")

@login_required(login_url="/")
def destroy_tipo_plantilla(request,pk):
    if request.method == "GET":
        try:
            tipo_plantilla = TipoPlantilla.objects.get(id=pk)
        except:
            return redirect("plantillas:tipos_plantillas")
        if request.user.is_superuser:
            tipo_plantilla.delete()
    return redirect("plantillas:tipos_plantillas")

templates/plantillas/plantillas_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    {% if request.user.is_staff %}
    <a href="{% url 'plantillas:agregar' %}" class="align-self-center ms-2 mb-1 btn btn-success text-light border"><i
            class="fas fa-plus-circle"></i> Agregar
        Plantilla</a>
    {% endif %}
</div>
<div class="table-responsive mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>Nombre</th>
                <th>Tipo</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for plantilla in object_list %}
            <tr>
                <td>{{plantilla.nombre}}</td>
                <td>{{plantilla.tipo}}</td>
                <td>{% if plantilla.activo %}<span class="badge badge-success">Activo</span>{% else %}<span
                        class="badge badge-danger">Inactivo</span>{% endif %}</td>
                <td>
                    {% if request.user.is_staff %}
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'plantillas:editar' pk=plantilla.id %}" id="edit"><i class="fas fa-edit"></i>
                        Editar</a>
                    {% endif %}
                    <a class="btn btn-danger btn-sm text-light border border-dark m-1"
                        href="{% url 'datos:ingreso_datos' pk_plantilla=plantilla.id get_fecha=None %}"
                        id="add_datos"><i class="fas fa-plus-circle"></i> Datos</a>
                    <!--Generar informe-->
                    <a class="btn btn-success btn-sm text-light border border-dark m-1"
                        href="{% url 'datos:generar_informe' pk_plantilla=plantilla.id %}" id="add_datos"><i
                            class="fas fa-plus-circle"></i> Generar Informe</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% endblock contenido %}
{% block javascript %}
<script>
</script>
{% endblock javascript %}

templates/plantillas/tipo_plantilla_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    {% if request.user.is_staff %}
    <a href="{% url 'plantillas:agregar_tipo_plantilla' %}"
        class="align-self-center ms-2 mb-1 btn btn-success text-light border"><i class="fas fa-plus-circle"></i> Agregar
        Tipo Plantilla</a>
    {% endif %}
</div>
<div class="table-responsive mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for tipo in object_list %}
            <tr>
                <td>{{tipo.nombre}}</td>
                <td>{{tipo.descripcion}}</td>
                <td>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'plantillas:editar_tipo_plantilla' pk=tipo.id %}" id="edit"><i
                            class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal"
                        data-popup-url="{% url 'plantillas:predestroy_tipo_plantilla' pk=tipo.id %}" href="">
                        <i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar el siguiente Tipo de Plantilla?:
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>


{% endblock contenido %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $(".dataTable").on('click', '.open-modal', function () {
            $.ajax({
                type: "GET",
                url: $(this).attr("data-popup-url"),
                dataType: "json",
                success: function (data) {
                    Datos =
                        "<p notempty='not'> ID: " + data['id'] +
                        "</p><p notempty='not'> Nombre: " + data['nombre'] +
                        "</p>";
                    $(".modal-body").append(Datos);
                    $("#delete").click(function () {
                        window.location.href =
                            "/plantillas/destroy_tipo_plantilla/" +
                            data["id"];
                    })
                }
            });
        });
        $("#close").on("click", function () {
            $(".modal-body").empty();
        })

        $('body').click(function (e) {
            if ($(e.target).attr('notempty') != "not")
                $(".modal-body").empty();
        });
    });
</script>
{% endblock javascript %}